# Generated by Django 2.2.5 on 2019-09-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='lat',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='lon',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
