# Generated by Django 2.2.5 on 2019-09-29 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_auto_20190929_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
