# Generated by Django 2.2.5 on 2019-09-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_auto_20190929_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
